name: nb-workflows

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.8, 3.9]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint with pylint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pylint --disable=R,C,W --ignore=rqjobs_bp.py,registers.py nb_workflows/
      - name: Test with pytest
        env:
          NB_SQL: postgresql://postgres:secret@postgres:5432/nb_workflows
          NB_ASQL: postgresql+asyncpg://postgres:secret@postgres:5432/nb_workflows

        run: |
          pytest --cov=nb_workflows tests/
 
